FROM node:22-bookworm-slim AS base

WORKDIR /app

RUN npm install -g bun


# 1. Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
# RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies using bun
COPY package.json bun.lockb* ./
RUN bun i

# 2. Copy the source code
FROM base AS dev
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Expose port 3000 for the app
EXPOSE 3000

# Set environment variables
ENV NODE_ENV=development
ENV PORT 3000
ENV HOSTNAME localhost
ENV NEXT_TELEMETRY_DISABLED 1

# Run the development server
CMD bun run dev
