version: "3"
services:
  database:
    build:
      context: ./backend/internal/database
      dockerfile: Dockerfile.prod
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - database
    ports:
      - "8888:8888"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  database-data:
