version: "3"
services:
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  backend-tester:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: tester # Use the tester build target

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend-tester
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/svelte.config.js:/app/svelte.config.js
