# --- BASE ---
FROM golang:alpine AS base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# --- TEST ---
FROM base AS tester
CMD go test ./... -coverprofile=coverage.out

# --- BUILD ---
FROM base AS builder
RUN go build -o main cmd/api/main.go

# --- RUN ---
FROM alpine:latest AS release

WORKDIR /app

# Copy the binary and script from the build stage
COPY --from=builder /app/main ./

EXPOSE 8888

CMD /app/main