FROM golang:alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /app

COPY . .
RUN go mod download
RUN chmod +x ./wait.sh

EXPOSE 8888

CMD ./wait.sh database:5432 -- go run server.go