# --- BUILD ---
FROM golang:alpine AS build-env

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest
COPY go.mod go.sum ./
RUN go mod download

# --- RUN ---
FROM golang:alpine

WORKDIR /app
COPY --from=build-env /go/pkg/mod /go/pkg/mod
COPY --from=build-env /go/bin/air /go/bin/air
COPY . .

EXPOSE 8888
CMD ["air"]