# Build stage
FROM golang:alpine AS build-env

# Set up the working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and the go.sum files are not changed
RUN go mod download

# Final stage
FROM golang:alpine

# Set up the working directory and copy over dependencies and source code
WORKDIR /app
COPY --from=build-env /go/pkg/mod /go/pkg/mod
COPY . .

EXPOSE 8888
CMD [ "go", "run", "server.go"]