FROM golang:alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

# Copy go mod and sum files first to leverage caching
COPY go.mod go.sum ./
RUN go mod download

COPY . .

FROM golang:alpine

WORKDIR /app

# Copy the source code and dependencies
COPY --from=builder /app ./

# Set Gin to release mode for testing
ENV GIN_MODE=release

CMD go test -coverprofile=coverage.out