# Build stage
FROM golang:alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

# Copy go mod and sum files first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Final stage
FROM golang:alpine

WORKDIR /app

# Copy the source code and dependencies
COPY --from=builder /app ./

CMD go test
