FROM golang:alpine AS builder

WORKDIR /app

# Copy go mod and sum files first to leverage caching
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main .

FROM alpine:latest

WORKDIR /app

# Copy the binary and script from the build stage
COPY --from=builder /app/main ./

EXPOSE 8888