// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Otp      *string `json:"otp,omitempty"`
	Phone    *string `json:"phone,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	Otp       *string `json:"otp,omitempty"`
	Phone     *string `json:"phone,omitempty"`
	CreatedAt int     `json:"createdAt"`
	UpdatedAt int     `json:"updatedAt"`
}
