// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ISomeService is an autogenerated mock type for the ISomeService type
type ISomeService struct {
	mock.Mock
}

type ISomeService_Expecter struct {
	mock *mock.Mock
}

func (_m *ISomeService) EXPECT() *ISomeService_Expecter {
	return &ISomeService_Expecter{mock: &_m.Mock}
}

// SomeMethod provides a mock function with given fields: ctx
func (_m *ISomeService) SomeMethod(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SomeMethod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISomeService_SomeMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SomeMethod'
type ISomeService_SomeMethod_Call struct {
	*mock.Call
}

// SomeMethod is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ISomeService_Expecter) SomeMethod(ctx interface{}) *ISomeService_SomeMethod_Call {
	return &ISomeService_SomeMethod_Call{Call: _e.mock.On("SomeMethod", ctx)}
}

func (_c *ISomeService_SomeMethod_Call) Run(run func(ctx context.Context)) *ISomeService_SomeMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ISomeService_SomeMethod_Call) Return(_a0 error) *ISomeService_SomeMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISomeService_SomeMethod_Call) RunAndReturn(run func(context.Context) error) *ISomeService_SomeMethod_Call {
	_c.Call.Return(run)
	return _c
}

// NewISomeService creates a new instance of ISomeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISomeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISomeService {
	mock := &ISomeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
